---
all:
  children:
    nginx:
       hosts:
         nginx1:
           ansible_host: "192.168.7.151"
           ansible_private_key_file: ".vagrant/machines/nginx1/virtualbox/private_key"
         nginx2:
           ansible_host: "192.168.7.152"
           ansible_private_key_file: ".vagrant/machines/nginx2/virtualbox/private_key"
    backend:
      hosts:
         backend1:
           ansible_host: "192.168.7.141"
           ansible_private_key_file: ".vagrant/machines/backend1/virtualbox/private_key" 
         backend2:
           ansible_host: "192.168.7.142"
           ansible_private_key_file: ".vagrant/machines/backend2/virtualbox/private_key"
         backend3:
           ansible_host: "192.168.7.143"
           ansible_private_key_file: ".vagrant/machines/backend3/virtualbox/private_key"
    dbms:
      hosts:
         dbms1:
           ansible_host: "192.168.7.161"
           ansible_private_key_file: ".vagrant/machines/dbms1/virtualbox/private_key" 
         dbms2:
           ansible_host: "192.168.7.162"
           ansible_private_key_file: ".vagrant/machines/dbms2/virtualbox/private_key" 
         dbms3:
           ansible_host: "192.168.7.163"
           ansible_private_key_file: ".vagrant/machines/dbms3/virtualbox/private_key" 
         dbms-router:
           ansible_host: "192.168.7.172"
           ansible_private_key_file: ".vagrant/machines/dbms-router/virtualbox/private_key" 
         dbms-shell:
           ansible_host: "192.168.7.171"
           ansible_private_key_file: ".vagrant/machines/dbms-shell/virtualbox/private_key" 
  vars:
    ntp_timezone: "UTC"
    password: "strong_pass"
